# Generated by Django 4.1.7 on 2023-03-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='SubCategory name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categ', to='main.category')),
            ],
        ),
    ]
