# Generated by Django 4.1.7 on 2023-03-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='SubCategory image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='SubCategory price'),
            preserve_default=False,
        ),
    ]
